require 'vagrant-lxc'

servers = [
  'puppet', 'node-1', 'node-2'
]

ubuntu_1404 = "https://swift.cloud.cybera.ca:8080/v1/AUTH_9aa5f9f66b4b417d84d778a23acdf45b/public/vagrant-lxc-trusty-amd64.box"

Vagrant.configure('2') do |config|
  config.ssh.username = 'ubuntu'
  config.vm.box = ubuntu_1404

  servers.each do |server|
    config.vm.define server do |s|

      shell_script = 'bootstraps/common.sh'

      case server
      when 'puppet'
        shell_script = 'bootstraps/puppet.sh'
        s.vm.provider :lxc do |lxc|
          lxc.container_name = server
          lxc.customize 'network.ipv4', '192.168.255.2'
        end
      when 'node-1'
        shell_script = 'bootstraps/node-1.sh'
        s.vm.provider :lxc do |lxc|
          lxc.container_name = server
          lxc.customize 'network.ipv4', '192.168.255.11'
        end
      when 'node-2'
        shell_script = 'bootstraps/node-1.sh'
        s.vm.provider :lxc do |lxc|
          lxc.container_name = server
          lxc.customize 'network.ipv4', '192.168.255.12'
        end
      end
    end
  end
end
