require 'vagrant-openstack-plugin'

Vagrant.configure("2") do |config|
  # "dummy" box because we're using Glance
  config.vm.box = "dummy"

  # Get homedir
  homedir = File.expand_path('~')

  # SSH
  config.ssh.private_key_path = "#{homedir}/.ssh/id_rsa"

  # Basic OpenStack options
  # Note that an openrc file needs sourced before using
  config.vm.provider :openstack do |os|
    os.username        = ENV['OS_USERNAME']
    os.api_key         = ENV['OS_PASSWORD']
    os.tenant          = ENV['OS_TENANT_NAME']
    os.flavor          = 'jt.large'
    os.image           = 'Ubuntu 14.04'
    os.endpoint        = "#{ENV['OS_AUTH_URL']}/tokens"
    os.keypair_name    = "home"
    os.ssh_username    = "ubuntu"
    os.security_groups = ['default']
    os.network         = 'cybera'
    os.networks        = []
  end

  # Loop through each server and define it
  config.vm.define 'ptact'
  config.vm.provision 'shell', path: 'bootstraps/ptact.sh'

end
